<?xml version='1.0'?>

<robot name="my_cart" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:property name="wheel_radius" value="0.10" />
  <xacro:property name="wheel_width" value="0.10" />
  <xacro:property name="footprint_width"  value="0.3" />
  <xacro:property name="footprint_height"  value="0.1" />
  <xacro:property name="footprint_length" value="0.5" />

  <xacro:include filename="$(find my_cart)/urdf/my_robot.gazebo" />

  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <joint name="robot_spoiler_joint" type="fixed">
    <origin xyz="-${footprint_length/2} 0 ${wheel_radius}" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="spoiler" />
  </joint>

  <joint name="robot_wings_joint" type="fixed">
    <origin xyz="${footprint_length/2*1.1} 0 ${-footprint_height/2*0.9}" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="wings" />
  </joint>

  <joint name="robot_driver_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="driver" />
  </joint>

  <joint type="fixed" name="smile_joint">
    <origin xyz="${footprint_width/6} 0 ${2*wheel_radius + 1*footprint_width/8}" rpy="0 0 0"/>
    <child link="smile"/>
    <parent link="chassis"/>    
  </joint>

  <link name='driver'>
    <visual name='driver_visual'>
      <origin xyz="0 0 ${wheel_radius}" rpy=" 0 0 0"/>
      <geometry>
          <cylinder radius="${footprint_width/6}" length="${2*wheel_radius}"/>
      </geometry>
    </visual>

    <visual name='dx_shulder_visual'>
      <origin xyz="0 -${footprint_width/6 + footprint_width/16} ${0.8*wheel_radius*2}" rpy=" 0 0 0"/>
      <geometry>
          <sphere radius="${footprint_width/10}"/>
      </geometry>
    </visual>

    <visual name='sx_shulder_visual'>
      <origin xyz="0 ${footprint_width/6 + footprint_width/16} ${0.8*wheel_radius*2}" rpy=" 0 0 0"/>
      <geometry>
          <sphere radius="${footprint_width/10}"/>
      </geometry>
    </visual>

    <visual name='dx_arm_visual'>
      <origin xyz="${0.8*wheel_radius} -${footprint_width/6 + footprint_width/16} ${0.8*wheel_radius}" rpy=" 0 -0.75 0"/>
      <geometry>
          <cylinder radius="${footprint_width/16}" length="${1.4*2*0.8*wheel_radius}"/>
      </geometry>
    </visual>

    <visual name='sx_arm_visual'>
      <origin xyz="${0.8*wheel_radius} ${footprint_width/6 + footprint_width/16} ${0.8*wheel_radius}" rpy=" 0 -0.75 0"/>
      <geometry>
          <cylinder radius="${footprint_width/16}" length="${1.4*2*0.8*wheel_radius}"/>
      </geometry>
    </visual>

    <visual name='neck_visual'>
      <origin xyz="0 0 ${2*wheel_radius}" rpy=" 0 0 0"/>
      <geometry>
        <cylinder radius="${footprint_width/8}" length="${footprint_width/4}"/>
      </geometry>
    </visual>

    <visual name='driver_head_visual'>
      <origin xyz="0 0 ${2*wheel_radius + footprint_width/4}" rpy=" 0 0.3 0"/>
      <geometry>
        <sphere radius="${footprint_width/4}"/>          
      </geometry>
    </visual>
  </link>

  <link name="smile">
    <visual name='smile_visual'>
      <origin xyz="0 0 0" rpy=" 0 1.7 0"/>
      <geometry>        
        <cylinder radius="${footprint_width/8}" length="${footprint_width/10}"/>
      </geometry>
    </visual>
  </link>


  <link name='wings'>    
    <visual name='wings_visual'>
      <origin xyz="${footprint_length/10} 0 0" rpy=" 0 0.3 0"/>
      <geometry>
        <box size="${footprint_length/5} ${1.2*footprint_width} 0.01"/>
      </geometry>
    </visual>
    <visual name='wings_visual'>
      <origin xyz="${footprint_length/10} -${footprint_width/2} 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${footprint_length/5} ${0.01} ${footprint_height/2}"/>
      </geometry>
    </visual>
    <visual name='wings_visual'>
      <origin xyz="${footprint_length/10} ${footprint_width/2} 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${footprint_length/5} ${0.01} ${footprint_height/2}"/>
      </geometry>
    </visual>
  </link>

  <link name='spoiler'>    
    <visual name='spoiler_visual'>
      <origin xyz="${footprint_length/10} 0 ${wheel_radius/2}" rpy=" 0 0.3 0"/>
      <geometry>
        <box size="${footprint_length/5} ${1.2*footprint_width} 0.01"/>
      </geometry>
    </visual>
    <visual name='spoiler_visual'>
      <origin xyz="${footprint_length/10} -${footprint_width/2} ${wheel_radius/4}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${footprint_length/5} ${0.01} ${3*wheel_radius/4}"/>
      </geometry>
    </visual>
    <visual name='spoiler_visual'>
      <origin xyz="${footprint_length/10} ${footprint_width/2} ${wheel_radius/4}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${footprint_length/5} ${0.01} ${3*wheel_radius/4}"/>
      </geometry>
    </visual>
  </link>

  <link name='chassis'>
    <pose>0 0 ${wheel_radius} 0 0 0</pose>
    <inertial>
      <mass value="8.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.001"
      />
    </inertial>

    <!--collision name='chassis_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size="${footprint_length} ${footprint_width} ${footprint_height}"/>
      </geometry>
    </collision-->

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${footprint_length*0.8} ${footprint_width} ${footprint_height}"/>
      </geometry>
    </visual>

    <visual name='chassis_visual1'>
      <origin xyz="${footprint_length/2*0.8} 0 -${footprint_height/8}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${footprint_length*0.3} ${footprint_width/2} ${3*footprint_height/4}"/>
      </geometry>
    </visual>

    <visual name='chassis_visual2'>
      <origin xyz="${footprint_length/2*0.8} 0 -${footprint_height/4}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${footprint_length*0.4} ${footprint_width/4} ${footprint_height/2}"/>
      </geometry>
    </visual>
  </link>

  <link name="front_left_wheel">
    <collision name='front_left_wheel_collision'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <visual name='front_left_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <visual name='front_left_rad_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${3*wheel_radius/4}" length="${wheel_width + 0.002}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1.0"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.001" ixy="0" ixz="0"
          iyy="0.001" iyz="0"
          izz="0.005"
      />
    </inertial>
  </link>

  <link name="front_right_wheel">
    <collision name='front_right_wheel_collision'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <visual name='front_right_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <visual name='front_right_rad_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${3*wheel_radius/4}" length="${wheel_width + 0.002}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1.0"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.001" ixy="0" ixz="0"
          iyy="0.001" iyz="0"
          izz="0.005"
      />
    </inertial>
  </link>

  <link name="back_left_wheel">
    <collision name='back_left_wheel_collision'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <visual name='back_left_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <visual name='back_left_rad_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${3*wheel_radius/4}" length="${wheel_width + 0.002}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1.0"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.001" ixy="0" ixz="0"
          iyy="0.001" iyz="0"
          izz="0.005"
      />
    </inertial>
  </link>

  <link name="back_right_wheel">
    <collision name='front_right_wheel_collision'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <visual name='back_right_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>

    <visual name='back_right_rad_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${3*wheel_radius/4}" length="${wheel_width + 0.002}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1.0"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <inertia
          ixx="0.001" ixy="0" ixz="0"
          iyy="0.001" iyz="0"
          izz="0.005"
      />
    </inertial>
  </link>

  <joint type="continuous" name="front_left_wheel_hinge">
    <origin xyz="${footprint_length/2.0  - wheel_radius} ${footprint_width/2.0} 0" rpy="0 0 0"/>
    <child link="front_left_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="40" velocity="100"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <joint type="continuous" name="front_right_wheel_hinge">
    <origin xyz="${footprint_length/2.0 - wheel_radius} -${footprint_width/2.0} 0" rpy="0 0 0"/>
    <child link="front_right_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="40" velocity="100"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <joint type="continuous" name="back_left_wheel_hinge">
    <origin xyz="${-footprint_length/2.0 + wheel_radius} ${footprint_width/2.0} 0" rpy="0 0 0"/>
    <child link="back_left_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="40" velocity="100"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <joint type="continuous" name="back_right_wheel_hinge">
    <origin xyz="${-footprint_length/2.0 + wheel_radius} ${-footprint_width/2.0} 0" rpy="0 0 0"/>
    <child link="back_right_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="40" velocity="100"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- ******* FRONT CAMERA ******* -->
      
  <link name="camera">
    <!--collision name='camera_collision'>
      <origin xyz="-${footprint_width/8} 0 0" rpy=" 0 1.57 0"/>
      <geometry>
        <cylinder radius="${footprint_width/10}" length="${footprint_width/4}"/>
      </geometry>
    </collision-->

    <visual name='camera_visual'>
      <origin xyz="-${footprint_width/8} 0 0" rpy=" 0 1.57 0"/>
      <geometry>
        <cylinder radius="${footprint_width/10}" length="${footprint_width/4}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 ${2*wheel_radius + 3*footprint_width/8}" rpy=" 0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"
      />
    </inertial>
  </link>

  <joint type="fixed" name="camera_joint">
    <origin xyz="${footprint_width/4} 0 ${2*wheel_radius + 2*footprint_width/8}" rpy="0 0.10 0"/>
    <child link="camera"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>
  <!-- ******* -->

  <!-- ******* LIDAR ******* -->
  <link name="hokuyo">
    <!--collision name='hokuyo_collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision-->

    <visual name='hokuyo_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://my_cart/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5"/>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"
      />
    </inertial>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="${footprint_length/2 + 0.05} 0 ${-footprint_height/2 }" rpy="3.1415 0 0"/>
    <child link="hokuyo"/>
    <parent link="chassis"/>
    <axis xyz="0 -1 0" rpy="0 0 0"/>
  </joint>
  <!-- ******* -->

<gazebo reference="front_left_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="front_right_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="back_left_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="back_right_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="chassis">
    <material>Gazebo/Red</material>
</gazebo>

<gazebo reference="spoiler">
    <material>Gazebo/Red</material>
</gazebo>

<gazebo reference="smile">
    <material>Gazebo/Red</material>
</gazebo>

<gazebo reference="camera">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="wings">
    <material>Gazebo/Red</material>
</gazebo>

</robot>

